
# server config info
server:
  port: 8080
  servlet:
    context-path: /meeting-user
# spring config info
spring:
  #datasource druid
  datasource:
    name: bootssm
    type: com.alibaba.druid.pool.DruidDataSource
    druid: #druid config
      url: jdbc:mysql://localhost:3306/nj-1901-pro?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      filters: stat
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  # template config info
  thymeleaf:
    cache: false # default true
    mode: LEGACYHTML5  # nekohtml

# mybatis spring config
mybatis:
  type-aliases-package: com.qfjy.bean
  mapper-locations: classpath:com/qfjy/mapper/*.xml
# log config info
logging:
  level:
    com.qfjy: info
  file: log/log.log

# spring boot dubbo
dubbo:
  application:
    name: boot-user-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880


